### ISSUE TITLE
Replacing the font icons by proper SVG icons

### ISSUE THREAD

**Issue by ghost** [hrefhref/news#12]
Otherwise it can lead to a crappy rendering like 
![fonticons](https://cloud.githubusercontent.com/assets/8963482/10122533/c4730ee2-651c-11e5-9b4a-67629ce1e045.png)

For instance, the vote arrows could be replaced by those you can find [here](http://osgiliath.blackcat.systems/arrows/noun_45893.svg) and [there](http://osgiliath.blackcat.systems/arrows/noun_45902.svg) (designed by the people at useiconic.com)

**Comment by hrefhref** [comment]
> it can lead to a crappy rendering like

That's because of a misconfiguration on the server side, which made it load from http and was not making firefox happy. i've [fixed it](https://github.com/hrefhref/news/commit/f0b009210d9df6c9fbefb543e0a81dd2cca1e013)

> For instance, the vote arrows could be replaced by those you can find here and there (designed by the people at useiconic.com)

Well.. since it was a config error, is that really necessary ? the actual font may be loaded from SVG depending on your browser, and useiconic.com seems to be [commercial](https://useiconic.com/purchase/).

**Comment by ghost** [comment]
> Well.. since it was a config error, is that really necessary ?

Not anymore, indeed :)

> useiconic.com seems to be commercial.

Not those ones because they are freely available on [The Nount Project](https://thenounproject.com/useiconic.com/collection/iconic/).
